version: '3.8'
# docker-autoscout-crawler should be running! in it elastic and co are defined
services:
    autoscout_meanvalupdater:
        build: ./docker-updatemeanvalues
        image: autoscout_meanvalupdater:latest
        container_name: autoscout_meanvalupdater
        #command: bash -c "python loadIntoElastic.py" # tail -F anything
        volumes:
            - ./data/input:/data/input
            - ./data/output:/data/output
        networks:
            - elastic

    # flaskQueryElastic:
    #     build: ./flaskHandler/
    #     image: flaskqueryelastic:latest
    #     container_name: flaskqueryelastic
    #     command: bash -c "python actors.py" 
    #     networks:
    #         - elastic
    #     ports:
    #         - "5000:5000"
    #     depends_on:
    #         - copy2Elastic
        
networks:
    elastic:
        external: # should join existing
            name: elastic
